### ISSUE TITLE
app crashes on moto defy

### ISSUE THREAD

**Issue by maninthemiddle01** [Phantast/smartnavi#10]
Hello Phantast,
I use the version of f-droid. Version 2.1.2f as well as Version 2.2.1f crashes after showing the welcome screen. Version 2.0.4 worked for me.
I use a motorola defy with cyanogenmod 11

**Comment by Phantast** [comment]
If you would use the PlayStore version, I would have already seen the crash, because a crash reporting tool (Crashlytics) is implemented in SmartNavi. 

As in F-Droid, these tools are not allowed due to untrusted repositories, it is hard to support here without seeing the stacktrace of the exception. 
If you download the PlayStore version, the crash would be reported and I could fix it for both, PlayStore and F-Droid version. 
If you are concerned about privacy issues regarding Crashlytics, [here](https://try.crashlytics.com/terms/) you can find their disclaimers.

**Comment by maninthemiddle01** [comment]
excuse me, but I do not have google play. Can I download the apk from somewhere else? (https://apps.evozi.com/apk-downloader/) isn't providing it toll now.

**Comment by ImAnnoying** [comment]
I have the same issue on CM 12.1. When I try to download PlayStore's version(through APKPure) it refuses to install.

**Comment by Phantast** [comment]
I just released version 2.2.2f.
It should fix the bug. F-Droid should compile the update within one or two days. Please report if the error is fixed.

**Comment by Phantast** [comment]
Update is now ready on F-Droid.

**Comment by maninthemiddle01** [comment]
Hey Phantast, thank you very much for the effort, but unfortunately it is the same behaviour like before (crashes after showing the welcome screen). Also I tried to install the version of APKPure, but it installs either. Maybe you can provide yourself an apk from the playstore?

**Comment by Phantast** [comment]
I compiled this playStore version for you and uploaded it into the folder: smartnaviapp/ Give it a try.
https://github.com/Phantast/smartnavi/blob/master/smartnaviapp/smartnaviapp-playstore-release.apk

**Comment by maninthemiddle01** [comment]
doesnt even install

**Comment by Phantast** [comment]
Did you uninstall the old version first? And did you allow installation of apps from unknown sources?

**Comment by maninthemiddle01** [comment]
yes, I also deleted the app data first

**Comment by Phantast** [comment]
Try this one: https://github.com/Phantast/smartnavi/blob/master/smartnaviapp/smartnaviapp-free-release.apk

**Comment by maninthemiddle01** [comment]
at least for me everything works now (installation and program) without crashing :)
Vielen lieben Dank :)

**Comment by Phantast** [comment]
Thanks for your feedback and for your patience! :) Other users will benefit from that!
