### ISSUE TITLE
Use offline maps OsmAnd

### ISSUE THREAD

**Issue by PanderMusubi** [Phantast/smartnavi#9]
Please, use the already maps already downloaded on the device by OsmAnd. Also the online map cache could be shared.

**Comment by Phantast** [comment]
Hi Pander, when you install SmartNavi and start using OpenStreetMap, the app checks if the folder "osmdroid" already exists and then uses this folder. If not, SmartNavi creates its own folder. Since version 2.2 you can change the folder to any location you want. So you should also be able to tell SmartNavi to use the maps, created by OsmAnd. DId this solve your problem?

**Comment by Phantast** [comment]
With version 2.4.0 Open Street Maps is no longer supported.

**Comment by PanderMusubi** [comment]
Why?

**Comment by Phantast** [comment]
Unfortunetaly with 2.4.0 MapquestOSM and Mapnik are no longer supported as map providers.
Due to low usage of these map sources and high maintenance effort according to the changes of Mapquest and new paid plans on their service, the support has ended. 
SmartNavi is a free app without ads or inApp billing, so I can just not afford paid plans for a low used feature.
